theme: jekyll-theme-hacker
title: "100 JavaScript Projects | alnahian2003"
description: "Interesting vanilla JS projects which helped me to understand the core concepts of JavaScript and it's fundamentals"
